export const SystemEventActions = {
  // Autenticazione
  USER_LOGIN:                  'USER_LOGIN',
  USER_LOGIN_GOOGLE:           'USER_LOGIN_GOOGLE',
  USER_LOGIN_FAILED:           'USER_LOGIN_FAILED',
  USER_LOGOUT:                 'USER_LOGOUT',
  USER_TOKEN_REVOKED:          'USER_TOKEN_REVOKED',

  // Utenti
  USER_CREATED:                'USER_CREATED',
  USER_UPDATED:                'USER_UPDATED',
  USER_ACTIVATED:              'USER_ACTIVATED',
  USER_DEACTIVATED:            'USER_DEACTIVATED',
  USER_DELETED:                'USER_DELETED',
  USER_PASSWORD_CHANGED:       'USER_PASSWORD_CHANGED',
  USER_ROLE_CHANGED:           'USER_ROLE_CHANGED',

  // Permessi
  PERMISSION_OVERRIDE_CREATED: 'PERMISSION_OVERRIDE_CREATED',
  PERMISSION_OVERRIDE_UPDATED: 'PERMISSION_OVERRIDE_UPDATED',
  PERMISSION_OVERRIDE_DELETED: 'PERMISSION_OVERRIDE_DELETED',

  // Analisi
  ANALYSIS_CREATED:            'ANALYSIS_CREATED',
  ANALYSIS_UPDATED:            'ANALYSIS_UPDATED',
  ANALYSIS_DELETED:            'ANALYSIS_DELETED',
  ANALYSIS_STATUS_CHANGED:     'ANALYSIS_STATUS_CHANGED',

  // Impostazioni di sistema
  SETTING_UPDATED:             'SETTING_UPDATED',

  // Configurazione
  PRODUCT_CREATED:             'PRODUCT_CREATED',
  PRODUCT_UPDATED:             'PRODUCT_UPDATED',
  PRODUCT_DELETED:             'PRODUCT_DELETED',
  ALARM_CREATED:               'ALARM_CREATED',
  ALARM_UPDATED:               'ALARM_UPDATED',
  ALARM_DELETED:               'ALARM_DELETED',
  IGNORED_ALARM_CREATED:       'IGNORED_ALARM_CREATED',
  IGNORED_ALARM_UPDATED:       'IGNORED_ALARM_UPDATED',
  IGNORED_ALARM_DELETED:       'IGNORED_ALARM_DELETED',
} as const;

export type SystemEventAction = typeof SystemEventActions[keyof typeof SystemEventActions];
