export const SystemEventActions = {
  // Autenticazione
  USER_LOGIN:                  'USER_LOGIN',
  USER_LOGIN_GOOGLE:           'USER_LOGIN_GOOGLE',
  USER_LOGIN_FAILED:           'USER_LOGIN_FAILED',
  USER_LOGOUT:                 'USER_LOGOUT',
  USER_TOKEN_REVOKED:          'USER_TOKEN_REVOKED',

  // Utenti
  USER_CREATED:                'USER_CREATED',
  USER_UPDATED:                'USER_UPDATED',
  USER_ACTIVATED:              'USER_ACTIVATED',
  USER_DEACTIVATED:            'USER_DEACTIVATED',
  USER_DELETED:                'USER_DELETED',
  USER_PASSWORD_CHANGED:       'USER_PASSWORD_CHANGED',
  USER_ROLE_CHANGED:           'USER_ROLE_CHANGED',

  // Permessi
  PERMISSION_OVERRIDE_CREATED: 'PERMISSION_OVERRIDE_CREATED',
  PERMISSION_OVERRIDE_UPDATED: 'PERMISSION_OVERRIDE_UPDATED',
  PERMISSION_OVERRIDE_DELETED: 'PERMISSION_OVERRIDE_DELETED',

  // Analisi
  ANALYSIS_CREATED:            'ANALYSIS_CREATED',
  ANALYSIS_UPDATED:            'ANALYSIS_UPDATED',
  ANALYSIS_DELETED:            'ANALYSIS_DELETED',
  ANALYSIS_STATUS_CHANGED:     'ANALYSIS_STATUS_CHANGED',

  // Impostazioni di sistema
  SETTING_UPDATED:             'SETTING_UPDATED',

  // Configurazione — Prodotti
  PRODUCT_CREATED:             'PRODUCT_CREATED',
  PRODUCT_UPDATED:             'PRODUCT_UPDATED',
  PRODUCT_DELETED:             'PRODUCT_DELETED',

  // Configurazione — Ambienti
  ENVIRONMENT_CREATED:         'ENVIRONMENT_CREATED',
  ENVIRONMENT_UPDATED:         'ENVIRONMENT_UPDATED',
  ENVIRONMENT_DELETED:         'ENVIRONMENT_DELETED',

  // Configurazione — Microservizi
  MICROSERVICE_CREATED:        'MICROSERVICE_CREATED',
  MICROSERVICE_UPDATED:        'MICROSERVICE_UPDATED',
  MICROSERVICE_DELETED:        'MICROSERVICE_DELETED',

  // Configurazione — Runbook
  RUNBOOK_CREATED:             'RUNBOOK_CREATED',
  RUNBOOK_UPDATED:             'RUNBOOK_UPDATED',
  RUNBOOK_DELETED:             'RUNBOOK_DELETED',

  // Configurazione — Azioni Finali
  FINAL_ACTION_CREATED:        'FINAL_ACTION_CREATED',
  FINAL_ACTION_UPDATED:        'FINAL_ACTION_UPDATED',
  FINAL_ACTION_DELETED:        'FINAL_ACTION_DELETED',

  // Configurazione — Allarmi
  ALARM_CREATED:               'ALARM_CREATED',
  ALARM_UPDATED:               'ALARM_UPDATED',
  ALARM_DELETED:               'ALARM_DELETED',

  // Allarmi scattati
  ALARM_EVENT_CREATED:         'ALARM_EVENT_CREATED',
  ALARM_EVENT_UPDATED:         'ALARM_EVENT_UPDATED',
  ALARM_EVENT_DELETED:         'ALARM_EVENT_DELETED',

  // Configurazione — Downstream
  DOWNSTREAM_CREATED:          'DOWNSTREAM_CREATED',
  DOWNSTREAM_UPDATED:          'DOWNSTREAM_UPDATED',
  DOWNSTREAM_DELETED:          'DOWNSTREAM_DELETED',

  // Configurazione — Allarmi Ignorati
  IGNORED_ALARM_CREATED:       'IGNORED_ALARM_CREATED',
  IGNORED_ALARM_UPDATED:       'IGNORED_ALARM_UPDATED',
  IGNORED_ALARM_DELETED:       'IGNORED_ALARM_DELETED',

  // Configurazione — Motivi di Ignoramento
  IGNORE_REASON_CREATED:       'IGNORE_REASON_CREATED',
  IGNORE_REASON_UPDATED:       'IGNORE_REASON_UPDATED',
  IGNORE_REASON_DELETED:       'IGNORE_REASON_DELETED',

  // Ruoli
  ROLE_CREATED:                'ROLE_CREATED',
  ROLE_UPDATED:                'ROLE_UPDATED',
  ROLE_DELETED:                'ROLE_DELETED',
  ROLE_PERMISSIONS_UPDATED:    'ROLE_PERMISSIONS_UPDATED',
} as const;

export type SystemEventAction = typeof SystemEventActions[keyof typeof SystemEventActions];
