import { SystemEventResources } from '../constants/system-event-resources.js';
import type { SystemEventResource } from '../constants/system-event-resources.js';
import { SystemEventActions } from '../constants/system-event-actions.js';
import type { SystemEventAction } from '../constants/system-event-actions.js';

export const SYSTEM_EVENT_RESOURCE_LABELS: Record<SystemEventResource, string> = {
  [SystemEventResources.AUTH]:                      'Auth',
  [SystemEventResources.USERS]:                     'Utenti',
  [SystemEventResources.ALARM_ANALYSES]:            'Analisi',
  [SystemEventResources.ALARM_EVENTS]:              'Allarmi Scattati',
  [SystemEventResources.SYSTEM_SETTINGS]:           'Impostazioni',
  [SystemEventResources.PRODUCTS]:                  'Prodotti',
  [SystemEventResources.ALARMS]:                    'Allarmi',
  [SystemEventResources.IGNORED_ALARMS]:            'Allarmi Ignorati',
  [SystemEventResources.ALARM_PRIORITY_RULES]:      'Regole Priority',
  [SystemEventResources.PRIORITY_LEVELS]:           'Livelli Priority',
  [SystemEventResources.USER_PERMISSION_OVERRIDES]: 'Override Permessi',
  [SystemEventResources.ENVIRONMENTS]:              'Ambienti',
  [SystemEventResources.RESOURCES]:                 'Risorse',
  [SystemEventResources.RUNBOOKS]:                  'Runbook',
  [SystemEventResources.FINAL_ACTIONS]:             'Azioni Finali',
  [SystemEventResources.DOWNSTREAMS]:               'Downstream',
  [SystemEventResources.IGNORE_REASONS]:            'Motivi Ignoramento',
  [SystemEventResources.RESOURCE_TYPES]:            'Tipi Risorsa',
  [SystemEventResources.ROLES]:                     'Ruoli',
};

export const SYSTEM_EVENT_ACTION_LABELS: Partial<Record<SystemEventAction, string>> = {
  [SystemEventActions.USER_LOGIN]:                  'Login',
  [SystemEventActions.USER_LOGIN_GOOGLE]:           'Login Google',
  [SystemEventActions.USER_LOGIN_FAILED]:           'Login Fallito',
  [SystemEventActions.USER_LOGOUT]:                 'Logout',
  [SystemEventActions.USER_TOKEN_REVOKED]:          'Token Revocato',
  [SystemEventActions.USER_CREATED]:                'Utente Creato',
  [SystemEventActions.USER_UPDATED]:                'Utente Aggiornato',
  [SystemEventActions.USER_ACTIVATED]:              'Utente Attivato',
  [SystemEventActions.USER_DEACTIVATED]:            'Utente Disattivato',
  [SystemEventActions.USER_DELETED]:                'Utente Eliminato',
  [SystemEventActions.USER_PASSWORD_CHANGED]:       'Password Cambiata',
  [SystemEventActions.USER_ROLE_CHANGED]:           'Ruolo Cambiato',
  [SystemEventActions.PERMISSION_OVERRIDE_CREATED]: 'Override Creato',
  [SystemEventActions.PERMISSION_OVERRIDE_UPDATED]: 'Override Aggiornato',
  [SystemEventActions.PERMISSION_OVERRIDE_DELETED]: 'Override Eliminato',
  [SystemEventActions.ANALYSIS_CREATED]:            'Analisi Creata',
  [SystemEventActions.ANALYSIS_UPDATED]:            'Analisi Aggiornata',
  [SystemEventActions.ANALYSIS_DELETED]:            'Analisi Eliminata',
  [SystemEventActions.ANALYSIS_STATUS_CHANGED]:     'Stato Analisi Cambiato',
  [SystemEventActions.SETTING_UPDATED]:             'Impostazione Aggiornata',
  [SystemEventActions.PRODUCT_CREATED]:             'Prodotto Creato',
  [SystemEventActions.PRODUCT_UPDATED]:             'Prodotto Aggiornato',
  [SystemEventActions.PRODUCT_DELETED]:             'Prodotto Eliminato',
  [SystemEventActions.ENVIRONMENT_CREATED]:         'Ambiente Creato',
  [SystemEventActions.ENVIRONMENT_UPDATED]:         'Ambiente Aggiornato',
  [SystemEventActions.ENVIRONMENT_DELETED]:         'Ambiente Eliminato',
  [SystemEventActions.RESOURCE_CREATED]:            'Risorsa Creata',
  [SystemEventActions.RESOURCE_UPDATED]:            'Risorsa Aggiornata',
  [SystemEventActions.RESOURCE_DELETED]:            'Risorsa Eliminata',
  [SystemEventActions.RUNBOOK_CREATED]:             'Runbook Creato',
  [SystemEventActions.RUNBOOK_UPDATED]:             'Runbook Aggiornato',
  [SystemEventActions.RUNBOOK_DELETED]:             'Runbook Eliminato',
  [SystemEventActions.FINAL_ACTION_CREATED]:        'Azione Finale Creata',
  [SystemEventActions.FINAL_ACTION_UPDATED]:        'Azione Finale Aggiornata',
  [SystemEventActions.FINAL_ACTION_DELETED]:        'Azione Finale Eliminata',
  [SystemEventActions.ALARM_CREATED]:               'Allarme Creato',
  [SystemEventActions.ALARM_UPDATED]:               'Allarme Aggiornato',
  [SystemEventActions.ALARM_DELETED]:               'Allarme Eliminato',
  [SystemEventActions.ALARM_EVENT_CREATED]:         'Allarme Scattato Creato',
  [SystemEventActions.ALARM_EVENT_UPDATED]:         'Allarme Scattato Aggiornato',
  [SystemEventActions.ALARM_EVENT_DELETED]:         'Allarme Scattato Eliminato',
  [SystemEventActions.DOWNSTREAM_CREATED]:          'Downstream Creato',
  [SystemEventActions.DOWNSTREAM_UPDATED]:          'Downstream Aggiornato',
  [SystemEventActions.DOWNSTREAM_DELETED]:          'Downstream Eliminato',
  [SystemEventActions.IGNORED_ALARM_CREATED]:       'Allarme Ignorato Creato',
  [SystemEventActions.IGNORED_ALARM_UPDATED]:       'Allarme Ignorato Aggiornato',
  [SystemEventActions.IGNORED_ALARM_DELETED]:       'Allarme Ignorato Eliminato',
  [SystemEventActions.PRIORITY_LEVEL_CREATED]:      'Livello Priority Creato',
  [SystemEventActions.PRIORITY_LEVEL_UPDATED]:      'Livello Priority Aggiornato',
  [SystemEventActions.PRIORITY_LEVEL_DELETED]:      'Livello Priority Eliminato',
  [SystemEventActions.ALARM_PRIORITY_RULE_CREATED]: 'Regola Priority Creata',
  [SystemEventActions.ALARM_PRIORITY_RULE_UPDATED]: 'Regola Priority Aggiornata',
  [SystemEventActions.ALARM_PRIORITY_RULE_DELETED]: 'Regola Priority Eliminata',
  [SystemEventActions.IGNORE_REASON_CREATED]:       'Motivo Ignoramento Creato',
  [SystemEventActions.IGNORE_REASON_UPDATED]:       'Motivo Ignoramento Aggiornato',
  [SystemEventActions.IGNORE_REASON_DELETED]:       'Motivo Ignoramento Eliminato',
  [SystemEventActions.RESOURCE_TYPE_CREATED]:       'Tipo Risorsa Creato',
  [SystemEventActions.RESOURCE_TYPE_UPDATED]:       'Tipo Risorsa Aggiornato',
  [SystemEventActions.RESOURCE_TYPE_DELETED]:       'Tipo Risorsa Eliminato',
  [SystemEventActions.ROLE_CREATED]:                'Ruolo Creato',
  [SystemEventActions.ROLE_UPDATED]:                'Ruolo Aggiornato',
  [SystemEventActions.ROLE_DELETED]:                'Ruolo Eliminato',
  [SystemEventActions.ROLE_PERMISSIONS_UPDATED]:    'Permessi Ruolo Aggiornati',
};
